### ISSUE TITLE
Tab and window commands on Manjaro Linux 

### ISSUE THREAD

**Issue by pepe** [alexherbo2/krabby#13]
I am trying to use Krabby on Manjaro Linux under SwayWM both in the Firefox Developer Edition and Chromium. Most of the commands (scrolling, selecting, clicking) work as expected, but none of the commands for tabs and windows is (t, n, x and so on).

In Firefox, there are no errors what so ever. It just does nothing. In Chromium, there are those errors in the console:

```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

```
extension.js:32 Uncaught Error: Attempting to use a disconnected port object
    at Object.KrabbyExtension.krabby.extensions.commands.send (extension.js:32)
    at Object.command (extension.js:145)
    at onKey (modal.js:210)
```

So it seems to me some process is not running. 

Can you please tell where to investigate so I can get you more information of what goes wrong with my setup?

PS: I am a big fan of your Kakoune works!

**Comment by alexherbo2** [comment]
Have you followed the installation steps in the script?

It seems you don’t have [Commands] installed.

[Commands]: https://github.com/alexherbo2/chrome-commands

**Comment by pepe** [comment]
I think I did. But let me try to go through it again and see what I did wrong. Thank you for your answer.

**Comment by pepe** [comment]
So I removed the extension from Firefox, `rm -rf .config/krabby`, `make install` in alexherbo2/krabby repo, then `make firefox` and `make chrome` in .config/krabby and add the extension to both browsers, but still without luck.

Here are outputs of commands and directory structure of ./config/krabby: https://gist.github.com/pepe/bae9ea5fa580ae22cee36d650c14b8fb

**Comment by alexherbo2** [comment]
Have you added the extensions in your browser?

I do not mean Krabby, but the other extensions.

**Comment by pepe** [comment]
Now I finally did. Sorry for the noise and wasting your time. Extension is great!
