### ISSUE TITLE
Can't search tabs and history

### ISSUE THREAD

**Issue by eyehol3** [alexherbo2/krabby#22]
[brave, macos 10.15.4]
when i press q or alt-q  nothing happens, chrome-dmenu is installed.

**Comment by alexherbo2** [comment]
[chrome-shell] too?

By default, [chrome-dmenu] uses [dmenu], which is not supported on macOS AFAIK.

[chrome-shell]: https://github.com/alexherbo2/chrome-shell
[chrome-dmenu]: https://github.com/alexherbo2/chrome-dmenu
[dmenu]: https://tools.suckless.org/dmenu/

---

Here are some links that might help you:

- https://github.com/alexherbo2/krabby/blob/master/docs/configuration.md#tab-search
- https://github.com/alexherbo2/configuration/blob/master/config/krabby/config.js

---

You can also see the error messages in `chrome://extensions` if something wrong happens.
