### ISSUE TITLE
Krabby Lite?

### ISSUE THREAD

**Issue by tshort** [alexherbo2/krabby#23]
For Chromebooks or Windows, it'd be nice to have a Lite version available for Chrome and Firefox in the appropriate stores. This would have to drop some features.

I was able to get Krabby installed in Chromium on Windows without extensions. No luck doing the same for Firefox.

**Comment by alexherbo2** [comment]
Full Krabby should work on Windows.  I just don’t have a Windows machine for testing and adding the stuff for installing.

---

I do not know Chromebook.  Can you have a shell for installing?

**Comment by tshort** [comment]
Chromebooks have a shell but only in development mode. I'm not sure if it's suitable for installing.

**Comment by alexherbo2** [comment]
@tshort Do you think you could add Windows support for Krabby and the extensions?

---

- https://github.com/alexherbo2/krabby/blob/master/docs/configuration.md#files



- https://github.com/alexherbo2/krabby/blob/master/Makefile
- https://github.com/alexherbo2/krabby/blob/master/scripts/install



- https://github.com/alexherbo2/chrome-shell/blob/master/host/Makefile
- https://github.com/alexherbo2/chrome-shell/blob/master/host/scripts/install-manifest
- https://github.com/alexherbo2/chrome-shell/blob/master/host/scripts/chrome-target.sh
- https://github.com/alexherbo2/chrome-shell/blob/master/host/scripts/chromium-target.sh
- https://github.com/alexherbo2/chrome-shell/blob/master/host/scripts/firefox-target.sh

**Comment by tshort** [comment]
I didn't have to change anything to get Krabby to install on Windows (without extensions). I ran the normal installation script in the `bash` prompt that comes with git (`make install extensions=no`). I did need to install `jq` before I did that.

Maybe it just needs some directions for this. Another way to approach it would be to write PowerShell scripts that mimic the unix shell scripts. I'm not touching that one. I will see how far I get with extensions. `dmenu` will be a problem.

**Comment by alexherbo2** [comment]
[chrome-shell] needs to be updated for the manifest host location.

[chrome-shell]: https://github.com/alexherbo2/chrome-shell

- https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-location
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location

[chrome-dmenu] does not need to be updated, because the `dmenu` program is configurable.

[chrome-dmenu]: https://github.com/alexherbo2/chrome-dmenu

- https://github.com/alexherbo2/krabby/blob/master/docs/configuration.md#tab-search

**Comment by alexherbo2** [comment]
It looks [Crystal] can be used with [WSL].

[Crystal]: https://crystal-lang.org
[WSL]: https://docs.microsoft.com/en-us/windows/wsl/

[Crystal – Install on WSL]

[Crystal – Install on WSL]: https://crystal-lang.org/install/on_wsl/
