### ISSUE TITLE
Disable krabby based on URL

### ISSUE THREAD

**Issue by mfzl** [alexherbo2/krabby#34]
Sometimes I require disabling the extension completely as it overrides some styles and keys. 

Mostly when doing local development involving browser. Is there a way to disable certain URLs, such as anything that starts with `http://localhost` or similar.

**Comment by alexherbo2** [comment]
Open your manifest — `~/.config/krabby/manifest/common.json`:

``` json
{
  "content_scripts": [
    {
      "exclude_matches": [
        "http://localhost/"
      ]
    }
  ]
}
```

Recompile your manifest:

``` sh
make -C ~/.config/krabby
```

See [Exclude matches and globs] for a complete reference.

[Exclude matches and globs]: https://developer.chrome.com/docs/extensions/content_scripts#matchAndGlob

**Comment by mfzl** [comment]
Should have mentioned that I'm using **Firefox 89.0b8 (64-bit)** on Linux

I tried the above config, but Firefox reports that extension is corrupt. Removing the line makes it work again.

**Comment by alexherbo2** [comment]
You might want to edit `~/.config/krabby/manifest/firefox.json` then.

**Comment by mfzl** [comment]
Thanks for the quick response @alexherbo2. 

It seems that `/` at the end of the URL is very significant. It doesn't work without it.

It works as you have put it, I missed the `/` first time around.

**Comment by mfzl** [comment]
![image](https://user-images.githubusercontent.com/1782950/119143908-98052480-ba61-11eb-8f9d-b7ad11b5a618.png)

Should have read the link you provided. In any case, thanks a lot

**Comment by alexherbo2** [comment]
Thanks a lot too.  You made me realize Chrome switched to [Manifest V3].

[Manifest V3]: https://developer.chrome.com/docs/extensions/mv3/intro/
