### ISSUE TITLE
Post releases

### ISSUE THREAD

**Issue by dzfranklin** [alexherbo2/krabby#7]
I'm very interested in trying this out, but not willing to run code as root to build a browser extension (required to install crystal-lang). Do you have any plans to post releases in the near future?

Best,
Daniel

**Comment by alexherbo2** [comment]
You don’t have to be root to build Krabby.  Just install the [dependencies] and run `make install` as a user.

I’m not sure about releases.  After installing, it’s your own Krabby that you build (Krabby never retouches your `~/.config/krabby`).  You can learn more about the file structure at [Configuration].

[Dependencies]: https://github.com/alexherbo2/krabby#dependencies
[Configuration]: https://github.com/alexherbo2/krabby/blob/master/doc/configuration.md

**Comment by dzfranklin** [comment]
The depe!dency crystal-lang has the requirement

**Comment by alexherbo2** [comment]
It’s a complaint about the dependencies then, not really Krabby requiring root.

To compile the application ([native messaging]) part, [Crystal] or [Docker] is required.

You can choose one of the following options:

- [Crystal]:

``` sh
make install
```

- [Docker] (for static builds):

``` sh
make install static=yes
```

[Native messaging]: https://developer.chrome.com/extensions/nativeMessaging
[Crystal]: https://crystal-lang.org
[Docker]: https://docker.com

**Comment by alexherbo2** [comment]
It’s a complaint about the dependencies then, not really Krabby requiring root.

To compile the application ([native messaging]) part, [Crystal] or [Docker] is required.

You can choose one of the following options:

- [Crystal]

``` sh
make install
```

- [Docker] (for static builds)

``` sh
make install static=yes
```

[Native messaging]: https://developer.chrome.com/extensions/nativeMessaging
[Crystal]: https://crystal-lang.org
[Docker]: https://docker.com

**Comment by dzfranklin** [comment]
Yes. I didn't realize the application involved native messaging, through it just built an application.
