### ISSUE TITLE
Add themes or allow to specify own stylesheet

### ISSUE THREAD

**Issue by micouy** [alexherbo2/krabby#8]
I think it would be cool to have an option to customize Krabby's look, especially the hints. When there are many elements on the page it becomes much less readable (at least that's my impression). For now I just edit the JS code.

Besides that, great work. I've just started testing and I really like it.

**Comment by alexherbo2** [comment]
[Appearance] from [Saka Key] will be a good start for [Hint].

It supports both options and custom CSS.

[Hint]: https://github.com/alexherbo2/hint.js
[Saka Key]: https://key.saka.io
[Appearance]: https://github.com/lusakasa/saka-key/tree/master/src/options/Appearance
