### ISSUE TITLE
Make installation instructions stand out in `make` output

### ISSUE THREAD

**Issue by micouy** [alexherbo2/krabby#9]
Adding boxes or making instructions for specific browser stand out more could help begginers and newcomers.

The `make` script spits out quite a lot of text. At the end of it there are further instructions. But the instructions for adding Krabby to the browser are not as visible as the last two boxes. I had no previous experience with third party extensions in my browser and there's no info on the website nor in README so I found it quite difficult to add Krabby as an extension. It simply says "*follow the onscreen instructions*".

![image](https://user-images.githubusercontent.com/20628866/71308820-65d13c80-2401-11ea-8324-0f3a232f2666.png)
There are many pages of text above that. At first it seemed like running `make` in `~/.config/krabby` is enough.

**Comment by alexherbo2** [comment]
The suggestion is to wrap browser instructions in text boxes, like at the end of the installation?

**Comment by micouy** [comment]
Yup, or use some other formatting. Just make it look important. Sorry if I wasn't clear.

**Comment by alexherbo2** [comment]
It will add some complexity to wrap the instructions in text boxes, because the path output is dynamic.

**Comment by micouy** [comment]
How about adding a header above that? **ADDING KRABBY TO YOUR BROWSER** or **INSTALLATION INSTRUCTIONS**. "*Installing:*" suggests that it's done by the script.

**Comment by alexherbo2** [comment]
I’m in if you want to make it clearer.

Normally, when you first install Krabby and `~/.config/krabby` does not exist yet, the [`install`] script runs interactively and pauses at each step.

Maybe we could enforce this by always running interactively, unless an option to disable it is passed.

[`install`]: https://github.com/alexherbo2/krabby/blob/master/scripts/install

**Comment by micouy** [comment]
I didn't see it on the first run either. It just blends in. I think you can just add an empty line and a bold/green/red/all caps header. It doesn't add any complexity to the code.

**Comment by alexherbo2** [comment]
@micouy Update your `Makefile` with the following changes and tell me if it’s better.  If you want to change the style, I can let you handle it.

[`~/.config/krabby/Makefile`]

``` makefile
interactive ?= yes

update:
	cd extensions/krabby; git pull; make static="$(static)" extensions="$(extensions)" interactive="$(interactive)"
```

[`~/.config/krabby/Makefile`]: https://github.com/alexherbo2/krabby/blob/master/share/krabby/Makefile
